获取锁失败之后----锁重试机制流程: [发布订阅]机制
- 如果tryLock()API中传入了最大等待时间,则说明开启了失败重试机制.
  通过源码分析,当第一次获取锁失败后且还处于等待时间时,不会立马再去尝试获取锁,
  而是先去订阅,订阅别人释放锁的信号,保证当有人执行完释放锁的lua脚本后它能监听到.
  但是一旦等待的时间超过了最大等待时间waitTime,就会取消订阅,不会重试了..
  订阅之后会在while(true)的一个死循环中不断的等待 尝试 等待 尝试....
  在释放锁的源码lua中,释放锁最后会发布一个释放锁的信号,这些订阅了的线程就会监听到!!!
  总结:并不是一种盲等,而是等获取到锁的线程释放了,基于发布订阅我再去尝试获取锁....